### ISSUE TITLE
Embed external sources

### ISSUE THREAD

**Issue by josefnpat** [robinmoisson/staticrypt#1]
This is a neat project, but it would be nice to be able to not depend on external sources; maybe add a checkbox that says "embed external sources"?

**Comment by oktvn** [comment]
I second this.

**Comment by EntranceJew** [comment]
I agree. I don't think the dependency upon jQuery should even be necessary in the generated pages. CryptoJS I understand completely, however.

**Comment by robinmoisson** [comment]
On the web I like the idea of the encrypted page being easily auditable and relying as little as possible on custom code inlined from an unknown repo - you might trust more libraries loaded over HTTPS from public, famous CDNs.

But I agree it would be nice to get a single file that is self contained and works offline as well. 

I'll definitely add the checkbox, thanks for the opened issue !

**Comment by qgustavor** [comment]
Why not replace dependencies with native versions?

* jQuery replaced with simple DOM manipulation:
    * `$(function () { ... })` is not needed as the script is in the end of the page
    * `$('#staticrypt-form').submit(...)` can be replaced with a `.addEventListener`
* crypto-js replaced with WebCrypto;
    * [HMAC example](https://github.com/diafygi/webcrypto-examples#hmac);
    * [AES-CBC example](https://github.com/diafygi/webcrypto-examples#aes-cbc) (CryptoJS defaults to AES-CBC);
    * [PBKDF2](https://github.com/diafygi/webcrypto-examples#pbkdf2) (why not?)
    * The only problem is compatibility (unlike jQuery which [is easy to fix](http://youmightnotneedjquery.com/));

**Comment by bfred-it** [comment]
This is fixed by #10 for the most part, only CryptoJS is loaded now.

**Comment by bfred-it** [comment]
@robinmoisson keep in mind that some ISPs/governments actually block CDNs so if you want it to work, it's best to include everything.

**Comment by robinmoisson** [comment]
@qgustavor Thanks for the pointer to WebCrypto, MDN marks it as still [experimental](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API#Browser_compatibility) and caniuses notes that

> Many browsers support the crypto.getRandomValues() method, but not actual cryptography functionality under crypto.subtle. 

When it is fully vetted and more widespread it might be an interesting addition to consider.

**Comment by bfred-it** [comment]
MDN is a wiki and is not always accurate. The Web Cryptography API has reached W3C Recommendation status in January: https://www.w3.org/TR/WebCryptoAPI/

**Comment by bfred-it** [comment]
+ Actual compatibility can be tested here: https://diafygi.github.io/webcrypto-examples/

**Comment by robinmoisson** [comment]
I added a checkbox to embed crypto-js (checked by default) in #13 (plus subresource integrity checks), it should do the trick for this issue feature wise - thanks for opening the issue :slightly_smiling_face: 

The info on WebCrypto is interesting, it should probably be a separated issue - we can detect if it is supported in the browser on the live website, but on the encrypted file if we don't embed crypto-js the file could only be unlocked with browsers that do support WebCrypto correctly. We could check which has a wider support...

I believe crypto-js is supposed to be pretty sturdy, do you see a drawback/advantage for switching?

**Comment by bfred-it** [comment]
@robinmoisson advantages:

- no dependencies
- smaller files

Drawbacks:

- slightly lower browser compatibility (which might not be as wide as you think already)
- gotta write it :D

**Comment by EntranceJew** [comment]
The main advantage I see to switching is portability, the major drawback I
see is being strung along by the lowest common denominator encryption
format w/o any way to upgrade when the time comes.

**Comment by robinmoisson** [comment]
Thanks for the good points guys :) 

I'm closing this issue as the "get a file with no dependency" feature is done and opening up a new one -> #20
