### ISSUE TITLE
Where do I place the hidden content?

### ISSUE THREAD

**Issue by sarobar** [robinmoisson/staticrypt#100]
So I am trying to create this content that can be accessed after entering the password. Currently whatever I place shows up with the passport prompt screen.

**Comment by sarobar** [comment]
Or how do I load the HTML after the password is entered?

**Comment by robinmoisson** [comment]
Are you using the web interface at https://robinmoisson.github.io/staticrypt/ ?

You should copy your html in the box labeled "HTML/string to encrypt", then click on Generate and then you can download your file with the green button, if you open that file with a browser and enter your passphrase your original html should automatically be displayed.

Let me know if I understood the issue correctly.
