### ISSUE TITLE
Pass template HTML file to CLI as argument

### ISSUE THREAD

**Issue by noamross** [robinmoisson/staticrypt#102]
Great tool! Suggestion: can the CLI allow the user to pass a custom template HTML file with `--template-file` / `-f` argument?

**Comment by robinmoisson** [comment]
Hi @noamross, yep it would make sense that users can customize the template, thanks for the suggestion!

**Comment by robinmoisson** [comment]
@noamross I added a way to do that, let me know if that fits your use case !
