### ISSUE TITLE
There shouldn't be any space before the exclamation point

### ISSUE THREAD

**Issue by plisker** [robinmoisson/staticrypt#106]
https://github.com/robinmoisson/staticrypt/blob/86391b34b7cbbcca1e11eb941a3d62e28be61d02/cli/password_template.html#L156

Per English convention, there shouldn't be a space before an exclamation point

**Comment by robinmoisson** [comment]
I see how that that can be annoying, thanks for reporting !

**Comment by plisker** [comment]
Thanks! 👍 Great product
