### ISSUE TITLE
how to add to Hugo Website?

### ISSUE THREAD

**Issue by ArchGalileu** [robinmoisson/staticrypt#110]
I would like to have some pages in my website made with hugo.

how can i?

Best regards 
ArchGalileu

**Comment by tarpdalton** [comment]
The immediate solution would be to use the cli version after you build your site. 
You would write a shell script that runs Hugo and then runs the cli to encrypt the published pages that you want encrypted. Then you would publish the static site. 

A cool solution would be to build staticcrypt into a Hugo template so that when you run Hugo it encrypts pages that have special front matter.

**Comment by ArchGalileu** [comment]
I don't know how to execute, but I will try ;)

of course on template would be great ;)

Best regards 
ArchGalileu

**Comment by ArchGalileu** [comment]
Ok i can't do it, i don't know how... but i understand ;)

i use npm but also don't know howyo prepare a script...

Can you give any hints?

Best regards
ArchGalileu

**Comment by robinmoisson** [comment]
Hi @ArchGalileu, I'm not very familiar with Hugo, a quick approach in pseudo code would be:

1. build your website locally, with the files you want to encrypt in a `<project_root>/website/secure` directory
2. run staticrypt cli on the `<project_root>/website/secure` files and delete the old files, for ex:

       # encrypt the files (see command from README)
       find <root_project>/website/secure -type f -name "*.html" -exec staticrypt {} <mypassword> \;
       # remove all non encrypted files from that folder - test it without `-delete` first, careful not to delete unwanted stuff !
       find <root_project>/website/secure -type f ! -name '*_encrypted.html' -delete

3. publish the website

You opened the issue a while ago, let me know if that's still relevant to you!

**Comment by edcous** [comment]
Hi, 
I'm having same problem. I've tried your commands and this is what I get:
10:45:47 AM: Build ready to start
10:45:49 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
10:45:49 AM: build-image tag: v3.3.2
10:45:49 AM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
10:45:49 AM: Fetching cached dependencies
10:45:49 AM: Starting to download cache of 255.0KB
10:45:49 AM: Finished downloading cache in 78.099206ms
10:45:49 AM: Starting to extract cache
10:45:49 AM: Failed to fetch cache, continuing with build
10:45:49 AM: Starting to prepare the repo for build
10:45:50 AM: No cached dependencies found. Cloning fresh repo
10:45:50 AM: git clone https://github.com/edcous/leahdemo
10:45:51 AM: Preparing Git Reference refs/heads/master
10:45:53 AM: Found netlify.toml. Overriding site configuration
10:45:53 AM: Different build command detected, going to use the one specified in the toml file: 'hugo && npm install && find /public -type f -name '*.html' -exec staticrypt {} password \ && find /public -type f ! -name '*_encrypted.html' \' versus 'hugo' in the site
10:45:53 AM: Starting build script
10:45:53 AM: Installing dependencies
10:45:55 AM: Downloading and installing node v10.16.0...
10:45:55 AM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
10:45:56 AM: 
######
10:45:56 AM:                              8.9%
10:45:56 AM: 
#########################################################
10:45:56 AM: ##               83.2%
10:45:56 AM: 
####################################################
10:45:56 AM: #################### 100.0%
10:45:56 AM: Computing checksum with sha256sum
10:45:56 AM: Checksums matched!
10:45:59 AM: Now using node v10.16.0 (npm v6.9.0)
10:45:59 AM: Attempting ruby version 2.6.2, read from environment
10:46:01 AM: Using ruby version 2.6.2
10:46:01 AM: Using PHP version 5.6
10:46:01 AM: Started restoring cached node modules
10:46:01 AM: Finished restoring cached node modules
10:46:01 AM: Installing NPM modules using NPM version 6.9.0
10:46:04 AM: added 55 packages from 18 contributors and audited 72 packages in 1.448s
10:46:04 AM: found 0 vulnerabilities
10:46:04 AM: NPM modules installed
10:46:04 AM: Installing Hugo 0.55.6
10:46:07 AM: Hugo Static Site Generator v0.55.6-A5D4C82D2/extended linux/amd64 BuildDate: 2019-05-18T08:08:34Z
10:46:07 AM: Started restoring cached go cache
10:46:07 AM: Finished restoring cached go cache
10:46:07 AM: unset GOOS;
10:46:07 AM: unset GOARCH;
10:46:07 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
10:46:07 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
10:46:07 AM: go version >&2;
10:46:07 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
10:46:07 AM: go version go1.12 linux/amd64
10:46:07 AM: Installing missing commands
10:46:07 AM: Verify run directory
10:46:07 AM: Executing user command: hugo && npm install && find /public -type f -name '*.html' -exec staticrypt {} password \ && find /public -type f ! -name '*_encrypted.html' \
10:46:07 AM: Building sites …
10:46:08 AM:                    | EN
10:46:08 AM: +
10:46:08 AM: ------------------+----+
10:46:08 AM:   Pages            | 20
10:46:13 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:46:08 AM:   Paginator pages  |  0
10:46:08 AM:   Non-page files   |  0
10:46:08 AM:   Static files     | 21
10:46:08 AM:   Processed images |  0
10:46:14 AM: Shutting down logging, 24 messages pending

**Comment by bsde1234** [comment]
> A cool solution would be to build staticcrypt into a Hugo template so that when you run Hugo it encrypts pages that have special front matter.
Is it possible, I am looking for this feature. Can you please tell me more how to acheive it?

**Comment by pixel-reverie** [comment]
Crypt.sh
```
#!/usr/bin/env bash
set -e

hugo && find ./public -type f -name "*.html" -exec staticrypt {} Sp00kySkeletons -f password_template.html -o {} \;
```

This will build and encrypt all your built html files for a hugo site.

As an aside, I have noticed consistent FOUC when using with Hugo.
