### ISSUE TITLE
Use key derivation and salting to fix rainbow table and brute-force attack opportunities

### ISSUE THREAD

**Issue by MaxLaumeister** [robinmoisson/staticrypt#113]
Hi! I am the writer of a very similar project:

https://github.com/MaxLaumeister/clientside-html-password

I just wanted to drop by to say: please consider using key derivation and salting in your crypto, so that users are less exposed to brute-force and rainbow table attacks.

You can read more here about why it's a good idea:

https://en.wikipedia.org/wiki/Key_(cryptography)#Key_vs_password

**Comment by robinmoisson** [comment]
I've been meaning to add it for a long time, it should be done now. Thank you for opening this issue !
