### ISSUE TITLE
Encrypting Multiple Pages

### ISSUE THREAD

**Issue by saifalfalah** [robinmoisson/staticrypt#114]
How does one encrypt multiple pages in a website? 

I mean, entering the password on one page decrypts all other pages at once. 

And all routes are protected as well.

**Comment by edcous** [comment]
Do you mean something like this:
> I have a Hugo website, using [Netlify](https://www.netlify.com), and would like to know how to not require all pages on the site to ask for the password if it has already been entered on another page. Any help would be greatly appreciated. The following is my Netlify build command
> `hugo && npm install && find public -type f -name '*.html' -exec staticrypt {} ****** \\;`
> Thanks,
> Eli

**Comment by robinmoisson** [comment]
Answer comes in pretty late - you can now use the "Remember me" checkbox to automatically decrypt all pages on the same domain

**Comment by saifalfalah** [comment]
Thank you!
