### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by b3hdad** [robinmoisson/staticrypt#115]
Hi,

I tried cryptojs with a bit larger files (~140 Meg) and it results in **uncaught exception: out of memory**. I even modified the code to open the file, read the content and pass it to the encryptor.

Any chance on fixing this?

Thanks.
Behdad.

**Comment by robinmoisson** [comment]
Thank you for reporting the issue - this would take a bit of work and I don't see it as the typical use case or myself working on that in the foreseeable future, so I'm closing for now. The current recommended solution is to increase the memory limit or not encrypt very large files with staticrypt. 

If more people have a use case for large HTML files please feel free to comment here as well (or open a PR) and I might re-open.
