### ISSUE TITLE
Native crypto module could not be used to get secure random number

### ISSUE THREAD

**Issue by dgarcia360** [robinmoisson/staticrypt#119]
``npx staticrypt index.html test -o index.html`` throws the following error:

> Native crypto module could not be used to get secure random number.

A quick fix could be to use a previous version of ``crypto-js``:
* https://github.com/brix/crypto-js/issues/256#issuecomment-584482094

**Comment by pushpender-singh-ap** [comment]
I have the same problem when installing this package into my react-native project.

**Comment by robinmoisson** [comment]
That's strange - `3.1.9-1` should be unaffected and this is the version staticrypt uses and embeds in the encrypted file. So I can't reproduce. It's been a while - if you're still experiencing the issue can you give more info on your setup, like running `npm i` and checking the crypto-js version in the package-lock.json?

**Comment by robinmoisson** [comment]
I can't reproduce but feel free to reopen / comment if you still have the issue.
