### ISSUE TITLE
Encryption won't work for all chars.

### ISSUE THREAD

**Issue by dave-ost** [robinmoisson/staticrypt#121]
Website encryption (https://robinmoisson.github.io/staticrypt) will work for all characters, CLI won't.
Result from CLI encryption (which worked with website):

¿Cómo está usted?    -->    �C�mo est� usted?

**Comment by robinmoisson** [comment]
I can't reproduce the issue with that string - on the CLI the input file is parsed as UTF-8 and if it's not encoded that way you might see this kind of error. You can try to change the file encoding to see if that fixes it.
