### ISSUE TITLE
If i turn on "remember me" on certain static html. not working

### ISSUE THREAD

**Issue by giorgiocc** [robinmoisson/staticrypt#129]
decryptAndReplaceHtml() working ->
it decrypts HTML. but not showing HTML javascript body
its just a blank page.

**Comment by robinmoisson** [comment]
Hello - I need more info to understand what's going on. Can you include:

- what is the the file you're trying to encrypt that's not working (or a working exemple to reproduce the issue)
- what is your password_template file if you're not using the default one
- is there any js error in the console when you you try to decrypt
- you're mentioning the "remember me" flag, what exactly are the steps you're taking and when does it fail?

Thanks.
