### ISSUE TITLE
Is there a way to put the password in the url and auto login?

### ISSUE THREAD

**Issue by dillfrescott** [robinmoisson/staticrypt#140]
This would be useful for sending out a private link to friends that could automatically log them in because the password is a url parameter! Is this possible?

**Comment by robinmoisson** [comment]
Thanks for the suggestion, could be interesting! I don't want to allow having the password in plaintext in the URL though, so it would be hashed just like the way it's stored in localStorage when checking "remember me".

What I'm thinking as an interface would be `staticrypt --share [optional url] MY_PASSWORD`, and that outputs something like `[example.com/foo/bar]?staticrypt_pwd=<hashed_password>` you can share to auto-decrypt the page. A GUI would have been nice but I don't think it makes sense on the html password prompt.

Would that fit your use case? Any feedback (from yourself or anyone) is welcome.

**Comment by dillfrescott** [comment]
Yes that would work! Thank you!

**Comment by oleteacher** [comment]
Would be a wonderful feature! Would help us when using staticrypt in the classroom to protect mock math tests.

**Comment by robinmoisson** [comment]
Staticrypt [new 2.2 release](https://github.com/robinmoisson/staticrypt/releases/tag/v2.2.0) now includes the `--share` flag - when you encrypt something and include this flag, it will output the shareable URL (or just the query param `?staticrypt_pwd=<hashed_password>` if you don't include your URL).

You have to encrypt a file to display the URL which feels a bit clumsy - staticrypt v3 will both include WebCrypto and do revamp of the CLI parameters, which will allow something like 

```bash
staticrypt -p <my_password> --share <my_optional_url>
```

without having to actually encrypt a file just to get the share URL, but this is a breaking change so it will have to wait the next version bump.

Thanks for opening the issue, let me know if there's anything else on that topic!

**Comment by robinmoisson** [comment]
The decryption logic has been updated on that release, it shouldn't break existing functionality on custom password templates but this new `share` feature depends on the new logic. 

So if you where using a custom password template the `share` feature will require you to update it.

**Comment by dillfrescott** [comment]
Awesome!
