### ISSUE TITLE
Page wont load after formatting template file with VS Code.

### ISSUE THREAD

**Issue by dth292** [robinmoisson/staticrypt#148]
I have to turn off VS code formatting to edit the template file.
You can take a look a the file by VS code default formatter.
[pwd_template_after_formatted_by_VSCode.zip](https://github.com/robinmoisson/staticrypt/files/10112091/pwd_template_after_formatted_by_VSCode.zip)

**Comment by robinmoisson** [comment]
Thanks for reporting. This makes sense - the password template is a template file and the templating style isn't standard, it just replacing `{special_key}` with some specific text. This means the password_template file isn't meant to be valid html (before replacement) and contains invalid javascript, so when VS code or any IDE tries to "fix it" it risks messing things up.

The official recommendation is to not run automatic code formatting on the password template (or fix it manually after each time).

That being said, I made a patch that makes the templating engine a little more flexible - in your example the breaking change was VS code adding spaces between brackets `{ special_key }`. With this patch your example file now works, but please consider it unofficial behavior.

---
If there are standard ways of telling auto formatters to ignore a chunk of code I could be open to adding those around the relevant part, but I guess there will be different for different tools (prettier, vs code, webstorm...) so I don't know if that would really work. Let me know if you have suggestions there.
