### ISSUE TITLE
Can't decrypt recently crypted links

### ISSUE THREAD

**Issue by cepreu5** [robinmoisson/staticrypt#151]
Hi,

I use https://robinmoisson.github.io/staticrypt/ to crypt some links for my one-page html app.

I'm changing these links every year.

The problem is that I can decrypt the links created last year, but when creating a new link with the same password the decrypt function doesn't decrypt it.

		encryptedHMAC = encryptedMsg.substring(0, 64);
		encryptedHTML = encryptedMsg.substring(64);
		decryptedHMAC = CryptoJS.HmacSHA256(encryptedHTML, CryptoJS.SHA256(passphrase).toString()).toString();

For old links encryptedHMAC/decryptedHMAC are equal, but for the newly created links they differ.

	function decrypt (encryptedMsg, pass) {
			var keySize = 256;
			var iterations = 1000;
			var salt = CryptoJS.enc.Hex.parse(encryptedMsg.substr(0, 32));
			var iv = CryptoJS.enc.Hex.parse(encryptedMsg.substr(32, 32))
			var encrypted = encryptedMsg.substring(64);
			var key = CryptoJS.PBKDF2(pass, salt, {
					keySize: keySize/32,
					iterations: iterations
			});
			var decrypted = CryptoJS.AES.decrypt(encrypted, key, {
					iv: iv,
					padding: CryptoJS.pad.Pkcs7,
					mode: CryptoJS.mode.CBC
			}).toString(CryptoJS.enc.Utf8);
			return decrypted;
	}

Are there any recent changes on staticrypt resulting in this issue? Please contact me at serbox@gmail.com if you need a detailed example and old and new encrypted strings for a test.

Happy New Year!
Sergey

**Comment by robinmoisson** [comment]
Hey Sergey - what version of Staticrypt are you using? Are you using a custom password template?

In February there was a [breaking change release](https://github.com/robinmoisson/staticrypt/releases/tag/v2.0.1) bumping the version number to 2.0. The salt is now passed separately from the ciphertext, to allow the remember-me feature to work.

If that's your issue you can either pin the staticrypt version to `< 2.0` or update your password template to handle the new parameters.

Does that look like this might be your issue?

**Comment by cepreu5** [comment]
Hi Robin,

Thank you for your answer!

I use Staticrypt from this link https://robinmoisson.github.io/staticrypt/ and don't see a way to "pin the staticrypt version to < 2.0" on site. I'm just encrypting the links to my Google drive spreadsheets which I use in my playn html app.

I've gotten the decrypt function, mentioned above, from your example site's html, so obviously I have to update it.

Thanks again and best wishes,
Sergey

**Comment by robinmoisson** [comment]
Hi Sergey - interesting, thanks for reporting more details. Yes, pinning the version only works when using staticrypt as a command line tool, the website always uses the latest version.

If you generate encrypted HTML from the website the embedded decryption logic should be renewed each time you generate the encrypted file, so you should be able to decrypt it through the page. Does it not work for you? 

Or are you using the content that's displayed in "Your encrypted string" and trying to decrypt that through your own process, so you're not using the generated "login" page? Or is your process something else?

Thanks!

**Comment by cepreu5** [comment]
Hi Robin!

Yes, I'm using the content that's displayed in "Your encrypted string" and I'm decrypting it through my own process.,  I updated it because I have my own login page which is displayed even when the "Remember me" was checked, so I have also "Forget" button on it. I also implemented encryption in my app and will not depend on future changes on your web site :-)

Best regards!
