### ISSUE TITLE
Question: How do we modify the login page?

### ISSUE THREAD

**Issue by AwesomeCaden73** [robinmoisson/staticrypt#153]
I'm sure it's really obvious, but I cannot for the life of me figure out how to modify the login page of the encrypted file. I use the web version - not the CLI - so I can't use a parameter. When I modify the template file (lib/password_template.html) itself, the output file doesn't seem to change at all.

**Comment by AwesomeCaden73** [comment]
I downloaded the repo and placed it in my web server, accessing index.html like I would a website. I'm using Edge at the moment (so Chromium).

**Comment by robinmoisson** [comment]
It should work when you modify the `password_template.html` file then yeah. This is where the password template file is downloaded: https://github.com/robinmoisson/staticrypt/blob/5dac008ba64490485db9a51b15e6b2f3adb2a145/index.html#L410

Is there cache on that file? If you check your network tab, is the file returned in ajax as expected when clicking download? Is it your modified file that's returned - if you replace the whole file with `<html>TEST</html>`, is that what you see in the ajax call and in the downloaded encrypted file?

**Comment by AwesomeCaden73** [comment]
There must have been something wrong with how I was saving the file changes - because somehow it works perfectly fine now.

How bizarre.

**Comment by robinmoisson** [comment]
Good to hear, thanks for updating!

**Comment by AwesomeCaden73** [comment]
I sort of figured it out... for some reason, my browser was caching both Staticrypt and the individual encrypted files. Clearing cookies and the browser cache didn't work - it was only when I used devtools to manually clear out everything for both that everything start working. I'm sure you don't remember, but ages ago I complained about the template page not updating... now I know why.
