### ISSUE TITLE
Add custom styling

### ISSUE THREAD

**Issue by royfrancis** [robinmoisson/staticrypt#162]
An option `--css` to add custom css stylesheet into the head of password_template.html.

**Comment by robinmoisson** [comment]
Thanks for the idea @royfrancis. It looks to me like this should be covered by using a custom password_template, which people can do. Do you see advantages to the `--css` solution you consider important?

**Comment by royfrancis** [comment]
Ideally, I think the template should be split into html, js and css. That makes it more flexible to make changes. Most people would want to change styling with css. The next level would be change the layout of the form (html). It's unlikely that the js would need to be changed.

Personally, I like the idea to using [bootstrap](https://getbootstrap.com/docs/5.3/forms/overview/) for styling. Removing the current styling and including the boostrap js and css to the html head makes it fit better with my project.

![Screenshot from 2023-03-27 13-31-26](https://user-images.githubusercontent.com/5083500/227931269-ed6a622c-504a-4abc-834f-4c3f22615da7.png)

**Comment by robinmoisson** [comment]
Hey @royfrancis , thanks for detailing and the pic - those rounded corners look good too.

I think allowing to set the full template as html is simpler. If the user wants to write code to customize the display we just hand over everything to them and they can edit the file however they want. Allowing to edit just the css doesn't feel like it makes things much simpler than editing the html to me and it's also more brittle: if I want to change something in the default password template later, having an external CSS file that point to it that I don't control means any change might break the CSS. 

Better for the two choices to be all-in, "use the full default template" or "use your own full custom template" I think.
