### ISSUE TITLE
Ability to decrypt with multiple passphrases

### ISSUE THREAD

**Issue by cyberboysumanjay** [robinmoisson/staticrypt#17]
Can this feature be implemented? 
Adding multiple passphrases to decrypt successfully.
 I'm still wondering if I can open a unique link instead of html when page is successfully decrypted?
If yes, how?

**Comment by robinmoisson** [comment]
Hi, I hear two subjects:

1. what do you mean by "open a unique link"? Be redirected somewhere once you click "decrypt" on the generated page?
2. multiple passphrases: each revealing a different output (for rubber-hose crypto for ex) or multiple valid passphrase for a single result?

**Comment by cyberboysumanjay** [comment]
1.  Yeah, redirected directly to a webpage instead of the encrypted html page. Like I encrypted www.google.com  and once I decrpyt  i'm directly redirected to google.com instead of that html page.

2. What I was asking was multiple valid passphrase for a single result but revealing a different output for multiple passphrases sounds awesome too!

**Comment by robinmoisson** [comment]
What's the use case for multiple correct password for a single content? Might add rubber hose in the future.

For the redirection the page encrypts a static html page only, I guess you could do it yourself by encrypting something that redirects in javascript by putting in the HTML section

    <script>
         window.location.replace("https://google.com");
    </script>

**Comment by cyberboysumanjay** [comment]
Redirection using script worked like a charm. Thanks!
