### ISSUE TITLE
Nothing is happening when clicking "decrypt" on encrypted pages

### ISSUE THREAD

**Issue by samantha-r-dzirko** [robinmoisson/staticrypt#176]
I'm trying to create an encrypted page using the online tool and I've also tried the downloaded project code.

### What's happening

When I open the downloaded file, enter the password then click "DECRYPT" this happens: nothing

### What should be happening

I expect this would happen instead: if the password is correct, then the page should decrypt and if the password is incorrect, I expect an alert box.

### My setup

StatiCrypt version: I'm assuming the latest because I'm using the web version https://robinmoisson.github.io/staticrypt/
Node version: n/a
Any additional relevant context, if any: The webpage worked as expected when I used it a few days ago. It's also worth noting that I've tried this in several browsers and have cleared cache multiple times. I've also tried it on a couple of different devices. Each time I experience the same behavior. 

https://user-images.githubusercontent.com/54124915/233899673-8aa665a2-77a2-4bd4-8dce-c51184e0d2b0.mp4

**Comment by robinmoisson** [comment]
Hi @samantha-r-dzirko, thank you for the detailed bug report an debugging steps, that's great.

I added the decrypt functionality to the CLI yesterday and it broke the online tool. I've just fixed and deployed it, it should work correctly now. Thank you for reporting so quickly.

**Comment by samantha-r-dzirko** [comment]
@robinmoisson Not a problem at all!

I just tested it, and it works as expected 😃 Thank you for swiftly diagnosing and fixing the online tool!
