### ISSUE TITLE
Did not generate encrypted content with "--share"

### ISSUE THREAD

**Issue by Nigh** [robinmoisson/staticrypt#182]
I want to generate encrypted content and the hash password at once:

`staticrypt .\example\index.html --short -p 123456 --share`

But this command just output the hash password only, which the line below could generates the encrypted content.

`staticrypt .\example\index.html --short -p 123456`

**Comment by robinmoisson** [comment]
Thanks for reporting - the behavior is as expected but the documentation is wrong, I'll fix that.

Behavior changed in staticrypt v3 which supports encrypting multiple files natively, to allow for getting the share link without having to re-encrypt something. I think another person was confused by the new behavior, so maybe this is debatable. I'd consider it a breaking change to change though, so it's now going to change right away. 

If you want to do both in a single command you'll have to do

```bash
staticrypt .\example\index.html --short -p 123456 && staticrypt --short -p 123456 --share
```

**Comment by robinmoisson** [comment]
(it's not* going to change right away)
