### ISSUE TITLE
Please update the home page interface to be compatible with mobile browsers

### ISSUE THREAD

**Issue by appxzm** [robinmoisson/staticrypt#185]
I hope that the UI interface of index will be updated next time, and it will be compatible with Android and IOS mobile phones. The interface is too ugly, please.

**Comment by robinmoisson** [comment]
Hi, what's incompatible with mobile browsers in the UI?

Concrete suggestions are welcome (with no guarantee that they'll lead to any change), but "too ugly" isn't actionable.

I just took a screenshot in firefox and possible improvements I see are:
- vertically centering the box
- removing the whiteband at the bottom (where the URL bar is before it hides on firefox)

If you want a different design you can also completely customize it with the `-t my_custom_template.html` parameter.

![Screenshot_20230830-095108](https://github.com/robinmoisson/staticrypt/assets/5664025/c5557968-57c3-4d0f-b2db-190ea375157a)

**Comment by alek-p** [comment]
working for me on mobile as well

**Comment by robinmoisson** [comment]
So I try vertically centering the box and I actually like it less than the current version. I'm closing this issue, if you have more specific feedback feel free to chime in.
