### ISSUE TITLE
Encrypt directories recursively but only HTML files

### ISSUE THREAD

**Issue by patrulea** [robinmoisson/staticrypt#188]
I’m using the latest Staticrypt version, `3.3.1`. The new `--recursive` feature really comes in handy. But is there a way to encrypt only HTML files within such directory? I’m running it on a Netlify project and I sure don’t want to modify non-HTML files like `_headers` and `_redirects` (JavaScript and CSS files may be affected as well, but haven’t tested those yet).

**Comment by robinmoisson** [comment]
Yes agreed, this is the topic of #181 - I'm fixing this now, thanks for reporting.

**Comment by robinmoisson** [comment]
Done & published! Starting 3.3.2, non-HTML file will be copied as-is.
