### ISSUE TITLE
Default AES-256-CBC mode vulnerabilities

### ISSUE THREAD

**Issue by good-lly** [robinmoisson/staticrypt#19]
If I am right, you are not setting any [specific encryption mode](https://stackoverflow.com/questions/1220751/how-to-choose-an-aes-encryption-mode-cbc-ecb-ctr-ocb-cfb)  thanks to that is used [default CBC mode](https://code.google.com/archive/p/crypto-js/) which can escalate into output vulnerabilities and [certain attacks](http://www.jakoblell.com/blog/2013/12/22/practical-malleability-attack-against-cbc-encrypted-luks-partitions/) ... did you consider to use some more proper modes? For example Galois-Counter Mode???

**Comment by RignonNoel** [comment]
@austin-rausch Do you want to explain why you put a thumbs-down ? Any expetise on the subject that you could share to help people understand the subject ?

**Comment by austin-rausch** [comment]
> @austin-rausch Do you want to explain why you put a thumbs-down ? Any expetise on the subject that you could share to help people understand the subject ?

No I don't remember the exact reason I put a thumbs down on an issue from 5 years ago. Its totally possible I pressed the wrong reaction, or didn't find the ultimate suggestion very helpful. Not sure, please don't bring me into discussions I never made a comment on. If I had anything to say I would have. Please do not reply to this or reach out to me anymore regarding this, I do not wish to continue this discussion.

Thank you and regards.

**Comment by robinmoisson** [comment]
Added thoughts on the malleability attack: we do sign the ciphertext with an HMAC, so this should guarantee data integrity. An attacker could remove that check happening client side but then again, if they can change the decryption logic they can do whatever they want.

**Comment by good-lly** [comment]
fair points
