### ISSUE TITLE
Where have i gone wrong?

### ISSUE THREAD

**Issue by BlitzdUK** [robinmoisson/staticrypt#192]
![0239-20022024png](https://github.com/robinmoisson/staticrypt/assets/36904558/e38d4cdc-193e-4cb7-8199-0c12390b2e2f)

**Comment by robinmoisson** [comment]
Hey @BlitzdUK, what command did you run to encrypt your file?

**Comment by robinmoisson** [comment]
I'm closing this, feel free to re-open if with more info if you'd like.
