### ISSUE TITLE
crypto.subtle missing on Safari iOS 17.3.1

### ISSUE THREAD

**Issue by jacksondc** [robinmoisson/staticrypt#194]
When I tap the decrypt button on my site on Safari (iOS 17.3.1), I get `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'subtle.importKey')`. It looks like the issue is because `window.crypto.subtle` is undefined. `window.crypto` looks like this:

<img width="349" alt="image" src="https://github.com/robinmoisson/staticrypt/assets/984955/e8aefd33-af04-4825-b41c-726f266d5673">

Curiously, the example page works fine, so I think this could be an issue with my configuration. Thought I'd ask in case anyone has ideas what could be causing this. I'm generating my site like

```
staticrypt <src>/* -r -p <password> -d <dest>
```

Thanks!

**Comment by jacksondc** [comment]
Oh shoot, I'll bet it's because I'm missing an SSL certificate 🤦

**Comment by jacksondc** [comment]
That was it!

**Comment by drzraf** [comment]
If you consider the impossibility to use the crypto API inside "non-secure" webcontext as a problem, here is a place to voice/thumb-up : https://github.com/w3c/webappsec-secure-contexts/issues/104
