### ISSUE TITLE
generation or download in Firefox 55.0a1

### ISSUE THREAD

**Issue by daveloyall** [robinmoisson/staticrypt#2]
I don't get any messages in the javascript console when I click 'generate' nor 'download'.  But, the downloaded document is truncated, less than 700 bytes.

If you give me instructions, I'll perform them to test this issue.

**Comment by robinmoisson** [comment]
Thanks for the report, I could reproduce it on my version of firefox (53.0.3) - the generated data is loaded in the `href` attribute of the download link, it seems chrome and firefox were escaping it differently.

It should be fixed now, do let me know if that does the trick for you.

**Comment by daveloyall** [comment]
You fixed it!
