### ISSUE TITLE
Replace crypto-js by browser native WebCrypto ?

### ISSUE THREAD

**Issue by robinmoisson** [robinmoisson/staticrypt#20]
Pro/Cons that I see:

**Pros**

- no dependencies at all
- smaller output (not a big issue I think, minified crypto-js is quite lean already)
- no need to update the lib, always as up to date as the browser

**Cons**

- at encryption time: I see it as going from using the crypto implementation of a single library that can be audited to leaving it to each user's browser, so the responsability of checking that their browser is up to date/bugfree on that point falls on each user. 

    Makes sense ? Is there any data on the crypto implementation of that API in browsers ?

- it might be nice to have a cli tool that can be inserted into one's workflow to update the encrypted files automatically. We can't use the browser API for that, crypto-js as a node library could also be used. Though the website and cli could use different tools.
- probably wider support (for now) for crypto-js but that'd need to be checked and by how much :)

Keeping in mind that it would be possible to use different solutions for encrypting/decrypting: encrypting needs to be the safest option, decrypting the most convenient one.

**Comment by tarpdalton** [comment]
Looks like it is supported for 88% of users: https://caniuse.com/#feat=cryptography

Chrome is only supported over [secure connections](https://bugs.chromium.org/p/chromium/issues/detail?id=373032) though.

Supported algorithms: https://diafygi.github.io/webcrypto-examples/

**Comment by robinmoisson** [comment]
Thanks for the data @tarpdalton! I agree it would be nice to use the webcrypto API - that would solve any potential adblocker misconfiguration and remove one more dependency. From your link local files seem to be considered a secure ressource by chrome which is good news.

The interface is less straightforward to deal with than cryptoJS but I've started looking into the implementation and hope to merge soon.

**Comment by tarpdalton** [comment]
[This gist](https://gist.github.com/chrisveness/43bcda93af9f646d083fad678071b90a) helped me understand the interface better. I'm not great with javascript, but it looks like the steps would be:

Encrypt
1. encode then digest/hash the password
1. generate the IV
1. encode then encrypt the text
1. encode, convert to hex, and concatenate the IV to the ciphertext

Decrypt
1. encode then digest/hash the password
1. split the IV off of the encrypted data
1. decode then decrypt

web crypto is promise based so it would require extra changes to the code

**Comment by tarpdalton** [comment]
Here is a [jsfiddle](https://jsfiddle.net/t97vqj75/1/) I got working with a password. It's pretty messy right now but it works. The annoying part is switching all the encodings back and forth.

**Comment by robinmoisson** [comment]
Thanks for the good work @tarpdalton !

Yep, the pain point definitely is the encoding part. The fiddle is quite nice, but when we use `asciiToUint8Array` we assume the text to encrypt is ascii - if we try to encrypt/decrypt `test 🐳` for example we get back `test =3`.

We could first convert the string to hex (https://stackoverflow.com/questions/21647928/javascript-unicode-string-to-hex) then use the `hexStringToUint8Array` to pass it to the webcrypto API and I'm guessing that should make us pretty much encoding agnostic.

**Comment by tarpdalton** [comment]
I got it to work for unicode instead of ascii, and I opened a PR #111 

There is still more work to get the CLI to work with webcrypto

**Comment by tom-sherman** [comment]
>  but when we use asciiToUint8Array we assume the text to encrypt is ascii

The browser has this build in via TextEncoder/TextDecoder.

https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API
