### ISSUE TITLE
No default body tag.

### ISSUE THREAD

**Issue by mini-eggs** [robinmoisson/staticrypt#3]
Found a nice edge case for ya 🗡 

Opening:
```html
<link href="https://fonts.googleapis.com/css?family=Lilita+One" rel="stylesheet">

<style>
  html {
    background-color: #f1f1f1;
    font-family: 'Lilita One', cursive;
    animation-duration: 5000ms;
    animation-fill-mode: both;
    animation-iteration-count: infinite;
    backface-visibility: visible;
    animation-name: colors;
    animation-timing-function: linear;
  }

  @keyframes colors {
    0% {
      transform: rotate3d(0deg);
      background-color: #f10a75;
      color: #fed024;
    }
    50% {
      background-color: #fed024;
      color: #f10a75;
    }
    100% {
      transform: rotateY(360deg);
      background-color: #f10a75;
      color: #fed024;
    }
  }

  body {
    margin: 0;
    text-align: center;
    line-height: 100vh;
  }

  body:after {
    content: "Coming Soon";
    font-size: 5vh;
  }
</style>
```
will display a spinning loading message, while after it has been ran through staticrypt it will not due to no default body tag being generated.

**Comment by bfred-it** [comment]
Are you sure this is the correct repo? That code is not part of `staticrypt`

**Comment by robinmoisson** [comment]
@mini-eggs Do you mean you encrypted that snippet and when you unlock it it behaves differently than if you open your snippet directly with a browser?

A full html page is expected (with `html` and `body` tags) to be decrypted then loaded correctly in browser, if you just use a fragment you might encounter different display behaviors. Most browsers try to fix HTML with missing tags on load page but you shouldn't really rely on it.

**Comment by mini-eggs** [comment]
> Do you mean you encrypted that snippet and when you unlock it it behaves differently than if you open your snippet directly with a browser?

Yes.

This is pretty up in the air to fix since it's not a best practice to rely on browsers fixing broken HTML, just thought it would be interesting to throw your way. If this tool requires/expects there to be valid HTML the no issue here

**Comment by robinmoisson** [comment]
If broken HTML is required for this issue to show up this feels slightly too edgy to me, people are a bit responsible for the display of what they encrypt :) Since the placeholder starts with `<html><head>...` it should be clear we expect all tags.

If you have a simple fix in mind feel free to open a PR and I'll look into it. Meanwhile I'm closing for now, thanks for testing and reporting !
