### ISSUE TITLE
Encrypt CLI

### ISSUE THREAD

**Issue by noobiemcfoob** [robinmoisson/staticrypt#97]
Would it be possible to make a CLI version of staticrypt that could be scripted into for automatic deployment?

I have several scripts that pull data and build html report pages. I'm imagining generating those pages as I do now, then running them through the staticrypt CLI to generate encrypted html pages I can then upload to my hosting service.

**Comment by robinmoisson** [comment]
Hi @noobiemcfoob, thanks for the suggestion. This has been on my mind for quite a while (probably as a npm package) but I have been too busy elsewhere so far to actually implement the feature.

I'll get to it whenever I can free some time :)

**Comment by robinmoisson** [comment]
CLI has been added thanks to original PR by @AaronCoplan, I'm closing !
