### ISSUE TITLE
CryptoJS.SHA256 without toString()

### ISSUE THREAD

**Issue by smondet** [robinmoisson/staticrypt#98]
I was trying to make a CLI shell script that does the generation side of staticrypt, and I can't seem to manage to reproduce the same HMAC with `openssl dgst`.

It seems that this line:
https://github.com/robinmoisson/staticrypt/blob/gh-pages/index.html#L200

```js
var hmac = CryptoJS.HmacSHA256(encrypted.toString(), CryptoJS.SHA256(passphrase)).toString();
```

is doing something maybe weird, or that I don't understand (?)

These two calls are doing something different:

```js
var hmac1 = CryptoJS.HmacSHA256("hello", CryptoJS.SHA256("key")).toString();
var hmac2 = CryptoJS.HmacSHA256("hello", CryptoJS.SHA256("key").toString()).toString();
```

gives:

```
hmac1: f1083d8619b5a4067c55eb2b718eca4a5340d7b297be894063893e596285d74e
hmac2: 613a0711a03eabab03c7a66d6e3d4debeef0926fcdab7666e1611a894ef40ed9
```

**Comment by abeudin** [comment]
there are salt that why is never same string. And i'm very interresting to help you to make CLI have you repo?

**Comment by smondet** [comment]
> there are salt that why is never same string.

no the HMac is deterministic, that's how staticrypt checks that the passphrase is the right one (the hmac is in the encrypted-page and it is compared to one computed from the user's input pass-phrase attempt).

e.g. with the second call (`hmac2`, with the `toString()`) you can reproduce the examples in wikipedia:
https://en.wikipedia.org/wiki/Hash-based_message_authentication_code#Examples

it also gives the same result with openssl:

```
printf  "The quick brown fox jumps over the lazy dog" | openssl dgst -sha256 -hmac "key"
(stdin)= f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8
```

>  have you repo?

Here I've pushed it: https://gitlab.com/smondet/staticrypt-cli
It works fine but with the `CryptoJS.SHA256("key").toString()` (2nd) version of the Hmac call instead of the one in this repo.

I really don't know what `CryptoJS.SHA256("key")` without the `toString()` gives to the Hmac function; with all the insanity of dynamic typing, it must be some implicit conversion.

**Comment by robinmoisson** [comment]
@smondet looking at cyptojs code it seems the following happens:

- `CryptoJS.SHA256("key")` resolves to an internal object, a `WordArray`
- calling `toString()` on it spits out an hexadecimal string
- the HMAC function needs a `WordArray` as a second parameter: either it gets one and goes straight to work, like in your first example, or it gets a string like in your second example and it converts it to a `WordArray`, but it expects it to be utf8 not specifically hex so it converts it to a different one

-> the `WordArray` it uses for the calculation end up being different

So looks like calling `toString` would make it easier to integrate with external tools (works for you after this modif?) & it should be added to the repo.

**Comment by smondet** [comment]
@robinmoisson yes with the `toString()` I can reproduce the hmac with openssl (and can also reproduce the examples on the wikipedia page). the script there https://gitlab.com/smondet/staticrypt-cli just does the job for me; but I'm no expert :)

If `CryptoJS.SHA256("key")` produces arbitrary word-arrays then it indeed makes it harder to work with when the other language has “C-style” strings (i.e. POSIX shells have a lot of trouble with `\x00` in the middle of a string).

**Comment by robinmoisson** [comment]
@smondet I just pushed the fix, thanks for opening the issue !
